name: TestPlugin
version: 1.0
main: jp.nagua.Main
commands:
    ping:
        description: show your ping.
        usage: /ping
    team:
        description: team command
        usage: /team [set/clear] [playerName] [red/blue]
depend: [ ProtocolLib ]